name: Build and test
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        env: [ubuntu-64, macos-64, windows-64]
        include:
          - env: ubuntu-64
            os: ubuntu-latest
          - env: macos-64
            os: macos-latest
          - env: windows-64
            os: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Rust toolchain for ${{ matrix.os }}
        uses: actions-rust-lang/setup-rust-toolchain@ac90e63697ac2784f4ecfe2964e1a285c304003a
      - name: Test for ${{ matrix.os }}
        uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505
        with:
          command: test
          args: --release --all-features
